/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import DataEstructure.Queue;
//import Helpers.ImageUtils;
import Classes.CharacterM;
import java.awt.FlowLayout;
import java.awt.Image;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

import javax.swing.JPanel;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author angel
 */
public class ColaUI extends javax.swing.JPanel {

    /**
     * Creates new form QueueUI
     */
    private JPanel queuePanel; // Panel para agregar los JLabel
    //private final ImageUtils imageUtils = new ImageUtils();

    public ColaUI() {
        initComponents();
        myInitComponents();
    }

    public ColaUI(String title) {
        initComponents();
        myInitComponents();
        
    }

    private void myInitComponents() {
        queuePanel = new JPanel();
        getQueuePanel().setLayout(new FlowLayout(FlowLayout.LEFT));
        jScrollPaneQueue.setViewportView(getQueuePanel());

        jScrollPaneQueue.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPaneQueue.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

    }

    public void addCard(String urlImage) {
        ImageIcon image = loadScaledImage(urlImage, 60, 60);
        JLabel etiqueta = new JLabel(image);
        getQueuePanel().add(etiqueta);
        
     
    }
    
    public ImageIcon loadScaledImage(String path, int width, int height) {
        URL imgUrl = getClass().getResource(path);
        if (imgUrl != null) {
            ImageIcon originalIcon = new ImageIcon(imgUrl);
            Image scaledImage = originalIcon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
            return new ImageIcon(scaledImage);
        } else {
            System.err.println("No se pudo encontrar el recurso: " + path);
            return null;
        }
    }
    
    

    public void updateQueueUI(Queue queue) {
        getQueuePanel().removeAll();
        Queue auxQueue = queue.cloneQueue();

        while (!auxQueue.isEmpty()) {
            CharacterM character = auxQueue.dequeue();
            this.addCard(character.getUrlIMG());
            
        }
        queuePanel.revalidate();
        queuePanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegularShowHighPriorityTitle = new javax.swing.JLabel();
        backgroundQueue = new javax.swing.JPanel();
        jScrollPaneQueue = new javax.swing.JScrollPane();

        RegularShowHighPriorityTitle.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        RegularShowHighPriorityTitle.setForeground(new java.awt.Color(0, 0, 0));
        RegularShowHighPriorityTitle.setText("COLA PRIORIDAD: ALTA");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundQueue.setBackground(new java.awt.Color(204, 204, 204));
        backgroundQueue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPaneQueue.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPaneQueue.setForeground(new java.awt.Color(204, 204, 204));
        backgroundQueue.add(jScrollPaneQueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 5, 340, 60));

        add(backgroundQueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 70));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RegularShowHighPriorityTitle;
    private javax.swing.JPanel backgroundQueue;
    private javax.swing.JScrollPane jScrollPaneQueue;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the queuePanel
     */
    public JPanel getQueuePanel() {
        return queuePanel;
    }

 
}
