/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import DataEstructure.Queue;
import java.awt.Image;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import proyecto2_sistemasoperativos.App;

/**
 *
 * @author gigie
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        battleDuration.setMinimum(1);
        battleDuration.setMaximum(10);
        battleDuration.setValue(App.getBattleDuration());
    }
    
    public void updateUIQueueSW(Queue queue1, Queue queue2, Queue queue3, Queue queue4){
        this.colaSW1.updateQueueUI(queue1);
        this.colaSW2.updateQueueUI(queue2);
        this.colaSW3.updateQueueUI(queue3);
        this.colaSW4.updateQueueUI(queue4);
    
    }
    
    public void updateUIQueueST(Queue queue1, Queue queue2, Queue queue3, Queue queue4){
        this.colaST1.updateQueueUI(queue1);
        this.colaST2.updateQueueUI(queue2);
        this.colaST3.updateQueueUI(queue3);
       this.colaST4.updateQueueUI(queue4);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        iaState = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        round = new javax.swing.JLabel();
        winStarTrek = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        cStarWars = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        cSWH = new javax.swing.JLabel();
        cSWL = new javax.swing.JLabel();
        cSWS = new javax.swing.JLabel();
        cSWT = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        cSWA = new javax.swing.JLabel();
        imgSW = new javax.swing.JPanel();
        cSWIMG = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        battleStatus = new javax.swing.JLabel();
        battleS = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        cStarTrek = new javax.swing.JLabel();
        cSTA = new javax.swing.JLabel();
        cSTH = new javax.swing.JLabel();
        cSTL = new javax.swing.JLabel();
        cSTS = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        cSTT = new javax.swing.JLabel();
        imgST = new javax.swing.JPanel();
        cSTIMG = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        winStarWars = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        battleDuration = new javax.swing.JSlider();
        colaSW2 = new Interfaz.ColaUI();
        colaSW3 = new Interfaz.ColaUI();
        colaSW4 = new Interfaz.ColaUI();
        colaST1 = new Interfaz.ColaUI();
        colaST2 = new Interfaz.ColaUI();
        colaST3 = new Interfaz.ColaUI();
        colaST4 = new Interfaz.ColaUI();
        colaSW1 = new Interfaz.ColaUI();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 68, -1, -1));

        jLabel1.setText("STAR TREK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, 20));

        jLabel2.setText("STAR WARS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel3.setText("De Refuerzo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 20));

        jLabel6.setText("2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel9.setText("Prioridad ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel10.setText("Prioridad ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel7.setText("1");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel12.setText("Prioridad ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel13.setText("Prioridad ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel8.setText("3");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel14.setText("Prioridad ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel15.setText("Prioridad ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel4.setText("De Refuerzo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, -1, 20));

        jLabel16.setText("2");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, -1, -1));

        jLabel17.setText("Prioridad ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, -1, -1));

        jLabel18.setText("Prioridad ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 310, -1, -1));

        jLabel20.setText("1");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, -1, -1));

        jLabel21.setText("Prioridad ");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, -1, -1));

        jLabel22.setText("Prioridad ");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, -1, -1));

        jLabel23.setText("3");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 250, -1, -1));

        jLabel24.setText("Prioridad ");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iaState.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iaState.setForeground(new java.awt.Color(0, 0, 0));
        iaState.setText("*estado*");
        jPanel12.add(iaState, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Victorias");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, -1));

        round.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        round.setForeground(new java.awt.Color(0, 0, 0));
        round.setText("0");
        jPanel12.add(round, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        winStarTrek.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        winStarTrek.setForeground(new java.awt.Color(0, 0, 0));
        winStarTrek.setText("0");
        jPanel12.add(winStarTrek, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 60, -1, -1));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Vida:");
        jPanel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Fuerza:");
        jPanel13.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Tipo:");
        jPanel13.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 20));

        cStarWars.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cStarWars.setForeground(new java.awt.Color(0, 0, 0));
        cStarWars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cStarWars.setText("Personaje");
        jPanel13.add(cStarWars, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 20));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Habilidad:");
        jPanel13.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        cSWH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cSWH.setForeground(new java.awt.Color(0, 0, 0));
        cSWH.setText("*h*");
        jPanel13.add(cSWH, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 20));

        cSWL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cSWL.setForeground(new java.awt.Color(0, 0, 0));
        cSWL.setText("Habilidad:");
        jPanel13.add(cSWL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 20));

        cSWS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cSWS.setForeground(new java.awt.Color(0, 0, 0));
        cSWS.setText("Habilidad:");
        jPanel13.add(cSWS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, 20));

        cSWT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cSWT.setForeground(new java.awt.Color(0, 0, 0));
        cSWT.setText("*");
        jPanel13.add(cSWT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 120, 20));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Agilidad:");
        jPanel13.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 20));

        cSWA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cSWA.setForeground(new java.awt.Color(0, 0, 0));
        cSWA.setText("*");
        jPanel13.add(cSWA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 60, 20));

        imgSW.setBackground(new java.awt.Color(255, 255, 255));

        cSWIMG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgSW.add(cSWIMG);

        jPanel13.add(imgSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, 170));
        imgSW.getAccessibleContext().setAccessibleName("");

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 250, 370));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Estado de la IA:");
        jPanel12.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        battleStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        battleStatus.setForeground(new java.awt.Color(0, 0, 0));
        battleStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        battleStatus.setText("*resultado*");
        jPanel12.add(battleStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 300, 20));

        battleS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        battleS.setForeground(new java.awt.Color(0, 0, 0));
        battleS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        battleS.setText(" ");
        jPanel12.add(battleS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 670, 20));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Habilidad:");
        jPanel14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Vida:");
        jPanel14.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Fuerza:");
        jPanel14.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Agilidad:");
        jPanel14.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 20));

        cStarTrek.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cStarTrek.setForeground(new java.awt.Color(0, 0, 0));
        cStarTrek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cStarTrek.setText("Personaje");
        jPanel14.add(cStarTrek, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 10, 240, 20));

        cSTA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cSTA.setForeground(new java.awt.Color(0, 0, 0));
        cSTA.setText("Habilidad:");
        jPanel14.add(cSTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, 20));

        cSTH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cSTH.setForeground(new java.awt.Color(0, 0, 0));
        cSTH.setText("Habilidad:");
        jPanel14.add(cSTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 20));

        cSTL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cSTL.setForeground(new java.awt.Color(0, 0, 0));
        cSTL.setText("Habilidad:");
        jPanel14.add(cSTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 20));

        cSTS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cSTS.setForeground(new java.awt.Color(0, 0, 0));
        cSTS.setText("Habilidad:");
        jPanel14.add(cSTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, 20));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Tipo:");
        jPanel14.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 20));

        cSTT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cSTT.setForeground(new java.awt.Color(0, 0, 0));
        cSTT.setText("*");
        jPanel14.add(cSTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, 20));

        imgST.setBackground(new java.awt.Color(255, 255, 255));

        cSTIMG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgST.add(cSTIMG);

        jPanel14.add(imgST, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, 170));

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 250, 370));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Victorias");
        jPanel12.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Ronda:");
        jPanel12.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        winStarWars.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        winStarWars.setForeground(new java.awt.Color(0, 0, 0));
        winStarWars.setText("0");
        jPanel12.add(winStarWars, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Tiempo:");
        jPanel12.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, 20));
        jPanel12.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Resultado de la batalla");
        jPanel12.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        battleDuration.setForeground(new java.awt.Color(0, 102, 102));
        battleDuration.setMajorTickSpacing(1);
        battleDuration.setMaximum(10);
        battleDuration.setMinimum(1);
        battleDuration.setPaintLabels(true);
        battleDuration.setPaintTicks(true);
        jPanel12.add(battleDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 380, 1100, 420));
        getContentPane().add(colaSW2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));
        getContentPane().add(colaSW3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));
        getContentPane().add(colaSW4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));
        getContentPane().add(colaST1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));
        getContentPane().add(colaST2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));
        getContentPane().add(colaST3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));
        getContentPane().add(colaST4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));
        getContentPane().add(colaSW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void battleDurationMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void battleDurationStateChanged(javax.swing.event.ChangeEvent evt) {                                            
        // TODO add your handling code here:
        int newSpeed = getBattleDuration().getValue();
//        
    }                                           

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider battleDuration;
    private javax.swing.JLabel battleS;
    private javax.swing.JLabel battleStatus;
    private javax.swing.JLabel cSTA;
    private javax.swing.JLabel cSTH;
    private javax.swing.JLabel cSTIMG;
    private javax.swing.JLabel cSTL;
    private javax.swing.JLabel cSTS;
    private javax.swing.JLabel cSTT;
    private javax.swing.JLabel cSWA;
    private javax.swing.JLabel cSWH;
    private javax.swing.JLabel cSWIMG;
    private javax.swing.JLabel cSWL;
    private javax.swing.JLabel cSWS;
    private javax.swing.JLabel cSWT;
    private javax.swing.JLabel cStarTrek;
    private javax.swing.JLabel cStarWars;
    private Interfaz.ColaUI colaST1;
    private Interfaz.ColaUI colaST2;
    private Interfaz.ColaUI colaST3;
    private Interfaz.ColaUI colaST4;
    private Interfaz.ColaUI colaSW1;
    private Interfaz.ColaUI colaSW2;
    private Interfaz.ColaUI colaSW3;
    private Interfaz.ColaUI colaSW4;
    private javax.swing.JLabel iaState;
    private javax.swing.JPanel imgST;
    private javax.swing.JPanel imgSW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel round;
    private javax.swing.JLabel winStarTrek;
    private javax.swing.JLabel winStarWars;
    // End of variables declaration//GEN-END:variables


    public javax.swing.JLabel getwinStarWars() {
        return winStarWars;
    }
    
    public void setIMGLabelSW(String root){
        ImageIcon image = loadScaledImage(root, 170, 170);   
        cSWIMG.setIcon(image);
                
    }
    
    public void setIMGLabelST(String root){
        ImageIcon image = loadScaledImage(root, 170, 170);   
        cSTIMG.setIcon(image);
                
    }
    
    
    
    public ImageIcon loadScaledImage(String path, int width, int height) {
        URL imgUrl = getClass().getResource(path);
        if (imgUrl != null) {
            ImageIcon originalIcon = new ImageIcon(imgUrl);
            Image scaledImage = originalIcon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
            return new ImageIcon(scaledImage);
        } else {
            System.err.println("No se pudo encontrar el recurso: " + path);
            return null;
        }
    }

    public JLabel getBattleS() {
        return battleS;
    }
    
    public javax.swing.JLabel getwinStarTrek() {
        return winStarTrek;
    }
    
    public javax.swing.JLabel getround() {
        return round;
    }
    
    public javax.swing.JLabel getbattleStatus() {
        return battleStatus;
    }
    
    public javax.swing.JLabel getiaState() {
        return iaState;
    }

    public JLabel getcSTA() {
        return cSTA;
    }

    public JLabel getcSTH() {
        return cSTH;
    }
    
    public JLabel getcSWH() {
        return cSWH;
    }
    
     public JLabel getcSWT() {
        return cSWT;
    }

    public JLabel getcSTT() {
        return cSTT;
    }

    public JLabel getcSTL() {
        return cSTL;
    }

    public JLabel getcSTS() {
        return cSTS;
    }

    public JLabel getcSWA() {
        return cSWA;
    }

    public JLabel getcSWL() {
        return cSWL;
    }

    public JLabel getcSWS() {
        return cSWS;
    }

    public JLabel getcStarTrek() {
        return cStarTrek;
    }

    public JLabel getcStarWars() {
        return cStarWars;
    }

    public JPanel getImgST() {
        return imgST;
    }

    public void setImgST(JPanel imgST) {
        this.imgST = imgST;
    }

    public JPanel getImgSW() {
        return imgSW;
    }

    public void setImgSW(JPanel imgSW) {
        this.imgSW = imgSW;
    }
    
     public javax.swing.JSlider getBattleDuration() {
        return battleDuration;
    }
    
    
    
    
    



}
